export const usageInstructions = [
  "1. 周中巡查：适用于平日/晚班Check。重点看：客人可见区域卫生、工作台面、抹布分区、出品动作、半成品、标签和员工空档主动补料。",
  "2. 周末高峰巡查：适用于周六/周日高峰2–3小时巡查：店长不主做产品，重点看物料齐备、物料质量、订单积压、客服疏导和现场环境。",
  "3. 评分方式：每项0/1/2分：2=稳定达标；1=小问题但可现场纠正；0=不达标或影响出品/顾客体验。",
  "4. 红线项：凡触发红线，请在“红线触发？”选择“是”。系统会自动判定不通过，需要当天纠正并反馈Owner。",
  "5. 周中新增重点：工作台面必须保持干净，因为顾客可以直接看到；抹布不能混用；有时间必须提前补齐抽屉物料和半成品，不要等断货。",
  "6. 周末新增重点：高峰前物料齐备情况，顾客等候与取餐动线疏导，以及员工应对等待的服务态度。",
  "7. Owner查看建议：低于70分或红线触发=必须复盘；70–79=安排针对性提醒；80–89=稳定但仍需抽查；90+=保持。",
  "8. 开早巡查评分：用于检查开门安全、设备预热、珍珠锅、Morning Clean、茶奶接管、冰槽/小料、打印/叫号、顾客区营业状态。",
  "9. 补料巡查评分：用于最后当班员工/补料责任人。检查小程序目标、牛奶/燕麦奶/杯子/吸管固定库存、premix规则、茶/foam/标签和异常上报。",
  "10. 晚清巡查评分：用于闭店清洁与安全。检查补料复核、珍珠锅、冰槽、奶茶机Day Clean、抹茶/foam、洗碗机、封口机、全店表面、垃圾地面与闭店安全。",
  "11. 使用建议：不要为了分数删除项目。评分表越细，越适合用于复训、责任追踪和稳定复制门店。"
];

export const dirEntries = [
  {
    page: "周中巡查评分",
    scene: "平日/晚班现场Check",
    focus: "客区、台面、出品、半成品、标签、主动补料",
    frequency: "每周2-3次抽查",
    low: "<70复训；70-79提醒",
    red: "当天纠正并反馈Owner",
  },
  {
    page: "周末高峰评分",
    scene: "周六/周日高峰2-3小时",
    focus: "断料风险、物料质量、订单积压、疏导、服务、环境",
    frequency: "每个周末至少1次",
    low: "高峰后复盘",
    red: "现场立即拦截",
  },
  {
    page: "开早巡查评分",
    scene: "开门到可营业状态",
    focus: "警报、设备、珍珠、Morning Clean、茶奶接管、打印叫号",
    frequency: "新员工/问题期高频抽查",
    low: "安排开早复训",
    red: "未完成不得营业",
  },
  {
    page: "补料巡查评分",
    scene: "最后当班/补料责任人",
    focus: "小程序目标、固定库存、premix规则、标签、异常上报",
    frequency: "每日闭店前/周末前重点查",
    low: "追踪责任人",
    red: "无标签/异常必须上报",
  },
  {
    page: "晚清巡查评分",
    scene: "闭店清洁与安全",
    focus: "补料复核、食材保存、Day Clean、冰槽、洗碗机、地面、警报锁门",
    frequency: "每日或抽查",
    low: "晚清复训/责任记录",
    red: "安全类立即处理",
  },
];

export const scoringData = [
  {
    name: "周中巡查评分",
    title: "ONESIP 周中巡查评分表",
    description: "适用于周中/晚班 Check：重点看客人可见卫生、出品稳定、标签食安、半成品准备和员工主动补料。",
    use_module_weight: false,
    total_weight: 565,
    items: [
      { module: "店面整洁&客区", item: "室内顾客桌面", standard: "桌面无杯印/糖渍/明显水渍；空档主动擦拭", weight: 20, is_redline: false },
      { module: "店面整洁&客区", item: "室外座位区", standard: "外摆桌椅整齐，桌面/地面无垃圾", weight: 20, is_redline: false },
      { module: "店面整洁&客区", item: "【红线】地面&动线", standard: "无明显垃圾、积水、黏腻；通道不堵", weight: 20, is_redline: true },
      { module: "店面整洁&客区", item: "点餐区/取餐区", standard: "前台不堆杂物，取餐台干净清楚", weight: 20, is_redline: false },
      { module: "店面整洁&客区", item: "【重点】客人可见工作台面", standard: "操作台/小料台干净，无糖渍、水渍、粉末、原料残留；客人看得到的位置必须保持整洁", weight: 20, is_redline: false },
      { module: "店面整洁&客区", item: "【红线】抹布分区使用", standard: "抹布不可混用；擦桌、擦台面、清洁地面/脏污的抹布必须分开", weight: 20, is_redline: true },
      { module: "店面整洁&客区", item: "垃圾桶", standard: "不超过八分满，无异味外溢；需要时及时换袋", weight: 20, is_redline: false },
      { module: "出品标准", item: "【红线】标准配方", standard: "不凭感觉改比例；糖冰/杯型/加料按订单执行", weight: 25, is_redline: true },
      { module: "出品标准", item: "混饮类动作", standard: "需要混饮的饮品有混匀；如“相遇”等不直接分层出杯", weight: 25, is_redline: false },
      { module: "出品标准", item: "抹茶类溶液", standard: "抹茶充分搅匀，无明显粉块/沉淀再交付", weight: 25, is_redline: false },
      { module: "出品标准", item: "奶茶机出品", standard: "颜色、浓度、甜度、温度/冰感稳定；异常及时反馈", weight: 25, is_redline: false },
      { module: "出品标准", item: "出杯检查", standard: "品名、糖冰、加料、杯身、封膜、标签出杯前检查", weight: 25, is_redline: false },
      { module: "半成品&小料", item: "珍珠煮制", standard: "软硬适中，不过硬不过烂；不结块", weight: 25, is_redline: false },
      { module: "半成品&小料", item: "珍珠清洗/过糖", standard: "清洗到位，糖浆状态正确，口感稳定", weight: 25, is_redline: false },
      { module: "半成品&小料", item: "【红线】奶盖状态", standard: "打发细腻，无颗粒/水油分离；未打好不得售卖", weight: 25, is_redline: true },
      { module: "半成品&小料", item: "小料&茶底库存", standard: "常用小料/茶底/奶底不断档，有提前补足意识", weight: 25, is_redline: false },
      { module: "半成品&小料", item: "【重点】抽屉物料补齐", standard: "有时间就补齐抽屉内物料、杯盖、吸管、标签等，不等到快用完才补", weight: 25, is_redline: false },
      { module: "半成品&小料", item: "【重点】半成品提前准备", standard: "珍珠、奶盖、茶底、常用小料按时段提前准备，避免下一班次或高峰断料", weight: 25, is_redline: false },
      { module: "半成品&小料", item: "半成品摆放", standard: "容器干净、封口好、位置清楚，不混放", weight: 25, is_redline: false },
      { module: "食安&标签", item: "【红线】开封标签", standard: "所有开封原料有名称、日期、时间、负责人", weight: 20, is_redline: true },
      { module: "食安&标签", item: "【红线】有效期检查", standard: "无过期、无标签不清仍继续使用的半成品/原料", weight: 20, is_redline: true },
      { module: "食安&标签", item: "【红线】冷藏保存", standard: "冷藏原料及时放回冰箱，不长时间室温暴露", weight: 20, is_redline: true },
      { module: "食安&标签", item: "【红线】消毒器/消毒液标签", standard: "有清楚标签和有效期；过期立即更换", weight: 20, is_redline: true },
      { module: "食安&标签", item: "【红线】工具分区", standard: "清洁用品与食品工具/冰铲/杯具分开放置", weight: 20, is_redline: true },
      { module: "氛围&员工状态", item: "灯光&音乐", standard: "灯光打开，音乐打开且音量合适", weight: 10, is_redline: false },
      { module: "氛围&员工状态", item: "员工状态", standard: "精神饱满，不冷脸、不懒散、不长时间玩手机", weight: 10, is_redline: false },
      { module: "氛围&员工状态", item: "服务沟通", standard: "招呼/解释/回应清楚，有礼貌，有耐心", weight: 10, is_redline: false },
      { module: "氛围&员工状态", item: "空档主动性", standard: "空档主动补料、擦台、整理客区，不等提醒", weight: 10, is_redline: false }
    ]
  },
  {
    name: "周末高峰评分",
    title: "ONESIP 周末高峰巡查评分表",
    description: "适用于周六/周日高峰2–3小时巡查：店长不主做产品，重点看物料齐备、物料质量、订单积压、客服疏导和现场环境。",
    use_module_weight: false,
    total_weight: 435,
    items: [
      { module: "物料齐备&断料风险", item: "高峰前物料齐备", standard: "巡查时确认杯子、吸管、封口膜、标签纸、冰块、常用小料已准备到位", weight: 30, is_redline: false },
      { module: "物料齐备&断料风险", item: "【红线】高峰不断料", standard: "珍珠、奶盖、茶底、奶底、果酱、爆珠等高频物料没有断料或明显不足", weight: 30, is_redline: true },
      { module: "物料齐备&断料风险", item: "抽屉/前台物料", standard: "抽屉内杯盖、吸管、标签、打包物料等补齐，员工忙时不用临时找", weight: 30, is_redline: false },
      { module: "物料齐备&断料风险", item: "下一班次准备", standard: "不忙时有推进下一班次所需物料/半成品准备，不把问题留到最后", weight: 30, is_redline: false },
      { module: "物料齐备&断料风险", item: "缺料反馈&安排", standard: "发现缺料风险能立即提醒当班员工补充，必要时反馈Owner/负责人", weight: 30, is_redline: false },
      { module: "物料质量&半成品状态", item: "珍珠状态", standard: "珍珠口感正常，清洗/过糖到位，无结块、过硬、过烂", weight: 25, is_redline: false },
      { module: "物料质量&半成品状态", item: "【红线】奶盖状态", standard: "奶盖打发合格，无明显颗粒、水油分离；失败奶盖不得继续卖", weight: 25, is_redline: true },
      { module: "物料质量&半成品状态", item: "茶底/奶底/果酱状态", standard: "颜色、气味、保存状态正常；无异常沉淀、变质风险", weight: 25, is_redline: false },
      { module: "物料质量&半成品状态", item: "半成品标签&摆放", standard: "半成品有标签、位置清楚、封口完整，不混放、不污染", weight: 25, is_redline: false },
      { module: "物料质量&半成品状态", item: "异常物料拦截", standard: "发现明显不合格物料，能暂停使用并现场提醒，不让问题流向顾客", weight: 25, is_redline: false },
      { module: "订单积压&现场疏导", item: "【红线】积压订单观察", standard: "巡查时观察订单量、等待时间、前台拥堵；发现积压必须及时疏导", weight: 20, is_redline: true },
      { module: "订单积压&现场疏导", item: "顾客等候/取餐动线", standard: "协助顾客理解取餐、等待和排队位置，避免门口/前台混乱", weight: 20, is_redline: false },
      { module: "订单积压&现场疏导", item: "现场沟通优先级", standard: "提醒员工先处理积压和高优先级订单；不替代制作，但要帮助现场顺起来", weight: 20, is_redline: false },
      { module: "订单积压&现场疏导", item: "高峰后恢复提醒", standard: "高峰后提醒员工快速恢复台面、客区、物料，不让现场持续混乱", weight: 20, is_redline: false },
      { module: "顾客服务&客诉处理", item: "等待回应", standard: "忙时有回应顾客等待，不让顾客一直无人理会", weight: 15, is_redline: false },
      { module: "顾客服务&客诉处理", item: "员工服务态度", standard: "员工语气稳定、礼貌，不急躁、不甩脸", weight: 15, is_redline: false },
      { module: "顾客服务&客诉处理", item: "缺料/错单处理", standard: "遇到缺料、错单、等太久时先道歉，再给清楚解决方案", weight: 15, is_redline: false },
      { module: "顾客服务&客诉处理", item: "【红线】客诉升级", standard: "复杂问题及时叫店长或Owner，不和顾客争辩", weight: 15, is_redline: true },
      { module: "环境卫生&门店氛围", item: "客区桌面&地面", standard: "店内外客区、桌面、地面保持可接受干净度，无明显垃圾/积水/糖渍", weight: 10, is_redline: false },
      { module: "环境卫生&门店氛围", item: "客人可见工作台面", standard: "前台和客人可见操作台保持干净，不能让顾客看到脏乱制作环境", weight: 10, is_redline: false },
      { module: "环境卫生&门店氛围", item: "垃圾桶&取餐区", standard: "垃圾不过满，取餐区干净清楚，不影响顾客体验", weight: 10, is_redline: false },
      { module: "环境卫生&门店氛围", item: "灯光&音乐&整体氛围", standard: "灯光打开，音乐正常，门店整体看起来有营业状态", weight: 10, is_redline: false }
    ]
  },
  {
    name: "开早巡查评分",
    title: "ONESIP 开早巡查评分表",
    description: "重点看安全解除、机器启动、奶茶机Morning Clean、茶奶接管、冰槽小料、打印叫号、顾客区营业状态。",
    use_module_weight: false,
    total_weight: 405,
    items: [
      { module: "进门&安全", item: "警报解除", standard: "按正确步骤解除警报；入店后先确认门店安全，再开始开早", weight: 10, is_redline: false },
      { module: "进门&安全", item: "明显异常检查", standard: "无漏水、异味、机器异常声、门窗异常；异常先拍照/视频并通知店长", weight: 10, is_redline: false },
      { module: "机器启动", item: "热水机/预热设备", standard: "热水机等需要预热机器已打开；热水机达到80°C以上再接水", weight: 15, is_redline: false },
      { module: "机器启动", item: "珍珠锅水量", standard: "每锅接2.6L热水，锅体放稳，盖子可正常盖上", weight: 15, is_redline: false },
      { module: "机器启动", item: "珍珠锅启动", standard: "排插/开关/Function/Start步骤正确，机器已开始加热", weight: 15, is_redline: false },
      { module: "机器启动", item: "珍珠加入", standard: "每锅700g珍珠；防腐剂包未入锅并已丢弃", weight: 15, is_redline: false },
      { module: "奶茶机准备", item: "Morning Clean", standard: "Auto Clean → Morning Clean → All Select；果糖/黑糖不选择；流程完整运行", weight: 20, is_redline: false },
      { module: "奶茶机准备", item: "清洁接水容器", standard: "出茶口下接水容器和导管位置正确，无漏水到台面", weight: 10, is_redline: false },
      { module: "配件归位", item: "晾晒配件归位", standard: "奶茶机滤器垫板、冰槽金属垫板、冰槽门、滤水垫板等归位", weight: 10, is_redline: false },
      { module: "配件归位", item: "洗碗机清空", standard: "勺子、桶、奶茶机大小容器取出并分类归位/备用", weight: 10, is_redline: false },
      { module: "配件归位", item: "Blender位置", standard: "抹茶blender放珍珠锅旁，大blender放奶茶机旁，不混放", weight: 5, is_redline: false },
      { module: "封口机", item: "封口机部件安装", standard: "上环、金属圈、橡皮圈、螺丝等装回，封口位置完整", weight: 10, is_redline: false },
      { module: "封口机", item: "封口机启动测试", standard: "机器已启动并可正常封口；营业前确认可用", weight: 10, is_redline: false },
      { module: "茶/奶/水上机", item: "Camellia煮制", standard: "Camellia茶叶200g煮4L；用白色细长2L茶桶分装，标签清楚", weight: 15, is_redline: false },
      { module: "茶/奶/水上机", item: "茶桶装量", standard: "工作日/周末茶量按标准；周末Jasmine和Black Tea 8L、Camellia 2L、水5L", weight: 15, is_redline: false },
      { module: "茶/奶/水上机", item: "先旧后新&标签转移", standard: "最旧茶放最外面优先用；转移效期标签到新容器", weight: 15, is_redline: false },
      { module: "茶/奶/水上机", item: "Oat Milk处理", standard: "Oat milk小容器装1L；不继续使用隔夜剩余oat milk", weight: 15, is_redline: false },
      { module: "茶/奶/水上机", item: "Milk处理", standard: "Milk大容器装3L；若保留milk，先检查标签和状态", weight: 15, is_redline: false },
      { module: "茶/奶/水上机", item: "接管&一键冲管", standard: "所有茶、奶、水、premix接管无错漏；一键冲管有接水容器", weight: 20, is_redline: false },
      { module: "冰槽/小料", item: "两个冰槽加冰", standard: "两个冰槽各加满1桶5L冰，营业初期不缺冰", weight: 10, is_redline: false },
      { module: "冰槽/小料", item: "罐头取出&保存盖", standard: "昨天保存罐头从指定小冰箱取出，打开透明盖；盖子收纳正确", weight: 10, is_redline: false },
      { module: "冰槽/小料", item: "小料和勺子", standard: "小料可营业使用；每个需要勺子的物料都有专用干净勺", weight: 10, is_redline: false },
      { module: "冰槽/小料", item: "小料缺料补齐&标签", standard: "缺料及时补齐，补料后贴效期标签", weight: 15, is_redline: false },
      { module: "抹布/顾客区", item: "抹布分区摆放", standard: "used盒抹布用热水洗净；按颜色和区域摆放，不混用", weight: 15, is_redline: false },
      { module: "抹布/顾客区", item: "垃圾袋", standard: "里侧大垃圾桶黑色袋；外面垃圾桶透明袋，均可正常使用", weight: 5, is_redline: false },
      { module: "设备/系统", item: "电视&叫号器", standard: "电视、叫号器正常显示/可用；遥控器未混淆", weight: 10, is_redline: false },
      { module: "设备/系统", item: "Kiosk供电", standard: "kiosk下面红色开关打开；异常按故障指引处理", weight: 10, is_redline: false },
      { module: "设备/系统", item: "Label printer & local printer", standard: "有纸、已连接，并实际测试可打印", weight: 15, is_redline: false },
      { module: "顾客区/营业状态", item: "顾客区桌椅", standard: "顾客桌用指定抹布擦净，椅子摆出，客区可入座", weight: 10, is_redline: false },
      { module: "顾客区/营业状态", item: "灯光&营业氛围", standard: "全店灯光打开，门店进入可营业状态", weight: 5, is_redline: false }
    ]
  },
  {
    name: "补料巡查评分",
    title: "ONESIP 补料巡查评分表",
    description: "重点看小程序目标、固定库存、premix容器规则、茶/foam/标签、异常上报和现场恢复。",
    use_module_weight: false,
    total_weight: 250,
    items: [
      { module: "小程序目标", item: "小程序补料完成", standard: "按管理小程序当日目标完成补料，并提交实际完成数量", weight: 30, is_redline: false },
      { module: "固定库存", item: "牛奶库存", standard: "柜子上的牛奶 ≥10盒", weight: 20, is_redline: false },
      { module: "固定库存", item: "燕麦奶库存", standard: "柜子上的燕麦奶 ≥2盒", weight: 15, is_redline: false },
      { module: "固定库存", item: "长杯库存", standard: "杯架后面未开封长杯3条", weight: 15, is_redline: false },
      { module: "固定库存", item: "短杯库存", standard: "杯架后面未开封短杯3条", weight: 15, is_redline: false },
      { module: "固定库存", item: "暖饮杯库存", standard: "杯架后面未开封暖饮杯1条", weight: 10, is_redline: false },
      { module: "固定库存", item: "吸管库存", standard: "冷藏小冰箱展示架下面2包未开封吸管；前柜台吸管补齐", weight: 15, is_redline: false },
      { module: "Premix规则", item: "小容器优先", standard: "Premix优先用奶茶机小容器；减少占位和浪费", weight: 10, is_redline: false },
      { module: "Premix规则", item: "3L桶存放", standard: "小容器满时用3L茶桶装premix，保鲜膜封口，放右下Premix Prepare区域", weight: 10, is_redline: false },
      { module: "Premix规则", item: "黑色1.5L桶专用", standard: "黑色1.5L桶只装dragon fruit，避免串味/混淆", weight: 5, is_redline: false },
      { module: "茶/foam/标签", item: "正确容器", standard: "4L茶桶用于常规茶；2L白色细长茶桶按指定用途，不乱装premix", weight: 10, is_redline: false },
      { module: "茶/foam/标签", item: "先旧后新摆放", standard: "同类茶一列，从里到外新到旧；最旧在最外面", weight: 15, is_redline: false },
      { module: "茶/foam/标签", item: "Foam刮净", standard: "厨师机和容器内foam用硅胶铲刮净，减少浪费，方便清洗", weight: 10, is_redline: false },
      { module: "茶/foam/标签", item: "Foam存放", standard: "Foam盖好盖子，放珍珠锅下面小冰箱，效期标签清楚", weight: 15, is_redline: false },
      { module: "茶/foam/标签", item: "所有补料有标签", standard: "所有补好的料必须有名称/日期/时间/负责人或可判断效期的信息", weight: 25, is_redline: false },
      { module: "异常上报", item: "做多/做错/库存异常", standard: "做多、做错、库存和小程序不一致时，及时通知店长并留记录", weight: 15, is_redline: false },
      { module: "现场恢复", item: "原料归位", standard: "补回自己使用过的所有原料到指定位置，台面无补料遗留", weight: 15, is_redline: false }
    ]
  },
  {
    name: "晚清巡查评分",
    title: "ONESIP 晚清巡查评分表",
    description: "重点看补料检查、食材保存、奶茶机Day Clean、冰槽拆洗、全店表面、洗碗机、垃圾地面、关机警报锁门。",
    use_module_weight: false,
    total_weight: 660,
    items: [
      { module: "补料检查", item: "检查补料完成", standard: "晚清前先按小程序和固定库存逐项检查补料是否完成", weight: 20, is_redline: false },
      { module: "补料检查", item: "未补齐通报", standard: "发现未补齐时通知店长及下一个当班员工，记录缺什么/差多少", weight: 15, is_redline: false },
      { module: "珍珠锅", item: "剩余珍珠保存", standard: "剩余珍珠用500ml杯封口、贴彩虹标，放楼下白色长冰箱", weight: 15, is_redline: false },
      { module: "珍珠锅", item: "珍珠锅清洗倒扣", standard: "热水+硬毛刷清洗，无珍珠/糖浆残留，悬空倒扣晾干", weight: 15, is_redline: false },
      { module: "珍珠锅", item: "珍珠锅桌面", standard: "喷清洁液静置约5分钟后擦净，无黏腻/污渍", weight: 10, is_redline: false },
      { module: "里侧冰槽", item: "罐头保存", standard: "冰槽罐头取出，未用完盖塑料盖，放珍珠锅下面小冰箱", weight: 15, is_redline: false },
      { module: "里侧冰槽", item: "勺子/收纳箱", standard: "勺子进洗碗机，透明收纳箱清洁，不留冰槽过夜", weight: 10, is_redline: false },
      { module: "里侧冰槽", item: "冰槽配件拆洗", standard: "金属垫板和抽拉门拆下，用热水和硬毛刷刷洗", weight: 15, is_redline: false },
      { module: "里侧冰槽", item: "冰槽内部清洁", standard: "1泵洗洁精+5L热水静置，再刷内壁并用5L热水冲净", weight: 20, is_redline: false },
      { module: "奶茶机", item: "头顶茶桶处理", standard: "逐个取下茶桶，按标签判断旧茶是否可留", weight: 10, is_redline: false },
      { module: "奶茶机", item: "旧茶保留规则", standard: "超过1L且效期安全才用干净容器保留；效期标签必须转移", weight: 20, is_redline: false },
      { module: "奶茶机", item: "茶桶清洗晾晒", standard: "茶桶逐个清洗，倒扣回原位，桶口留缝隙通风", weight: 10, is_redline: false },
      { module: "奶茶机", item: "黑色底座/茶桶盖", standard: "黑色放茶杯区域擦净；5个茶桶盖洗净并依次放好", weight: 10, is_redline: false },
      { module: "奶茶机", item: "第二层容器处理", standard: "拔管；低于出茶管刻度的容器拿出初洗后进洗碗机", weight: 15, is_redline: false },
      { module: "奶茶机", item: "Oat Milk处理", standard: "Oat milk容器必须移除清洁；剩余oat milk倒掉并报损", weight: 20, is_redline: false },
      { module: "奶茶机", item: "小料区清洁", standard: "先移除勺子进洗碗机，再擦净小料区下方粉末/糖渍/黏腻", weight: 15, is_redline: false },
      { module: "奶茶机", item: "金属盖清洗", standard: "每个金属盖在水槽热水下冲洗干净再盖上", weight: 10, is_redline: false },
      { module: "奶茶机", item: "底部冰箱容器", standard: "拔管；低液位容器拿出初洗后进洗碗机", weight: 15, is_redline: false },
      { module: "奶茶机", item: "Milk处理", standard: "Milk容器移除清洁；剩余milk装干净容器，放右下Premix Prepare区域最外", weight: 20, is_redline: false },
      { module: "奶茶机", item: "过滤金属垫板", standard: "出茶口下方过滤金属垫板拆下热水+硬毛刷刷洗", weight: 10, is_redline: false },
      { module: "奶茶机Day Clean", item: "Day Clean准备", standard: "两个5L桶区分清洁液/清水；专用管连接正确；出茶口和导管位置安全", weight: 20, is_redline: false },
      { module: "奶茶机Day Clean", item: "导管复查", standard: "所有容器导管已拔除并连接到清洁口，无遗漏", weight: 20, is_redline: false },
      { module: "奶茶机Day Clean", item: "Day Clean执行", standard: "Auto Clean → Day Clean → All Select；果糖/黑糖不选择；流程完整运行", weight: 30, is_redline: false },
      { module: "奶茶机Day Clean", item: "出茶口水槽清洁", standard: "1泵洗洁精+3L热水静置，擦净出茶口/下方污渍/内壁，再3L热水冲净", weight: 15, is_redline: false },
      { module: "外侧冰槽/抹茶/foam", item: "Foam处理", standard: "效期安全则盖盖子放珍珠锅下面小冰箱，标签清楚；不安全处理", weight: 15, is_redline: false },
      { module: "外侧冰槽/抹茶/foam", item: "抹茶处理", standard: "每天结束倒掉抹茶并在小程序报损", weight: 20, is_redline: false },
      { module: "外侧冰槽/抹茶/foam", item: "抹茶容器手洗", standard: "抹茶容器必须手洗，无绿色残留", weight: 10, is_redline: false },
      { module: "外侧冰槽/抹茶/foam", item: "外侧冰槽拆洗", standard: "金属垫板和抽拉门拆下热水+硬毛刷清洗；内壁洗洁精热水静置后刷洗冲净", weight: 20, is_redline: false },
      { module: "晾晒&洗碗机", item: "晾杯垫和晾晒区", standard: "两个晾杯垫洗净放内街临窗桌；湿容器倒扣/通风，不叠放", weight: 10, is_redline: false },
      { module: "晾晒&洗碗机", item: "洗碗机物品规则", standard: "可机洗物品进洗碗机；软塑料和blender配件不进洗碗机", weight: 15, is_redline: false },
      { module: "晾晒&洗碗机", item: "洗碗机启动", standard: "先关闭热水机；放1块清洁块；按P3启动", weight: 20, is_redline: false },
      { module: "封口机", item: "封口机拆洗", standard: "进入Manual，拆两颗螺丝、上环、金属圈、橡皮圈并洗净", weight: 15, is_redline: false },
      { module: "封口机", item: "小零件归位&关机", standard: "部件和螺丝放一起；封口区域擦净；封口机关闭", weight: 15, is_redline: false },
      { module: "全店表面", item: "金属/机器/柜门", standard: "所有金属表面、奶茶机、珍珠锅、冰槽、制冰机、热水机等喷清洁剂并擦净", weight: 20, is_redline: false },
      { module: "全店表面", item: "前台/客区/屏幕", standard: "前台、柜门壁、出茶盘、平板、顾客桌、kiosk屏幕均干净", weight: 20, is_redline: false },
      { module: "抹布/垃圾/地面", item: "抹布处理", standard: "所有用过抹布放used盒，加入1泵洗洁精和热水浸泡", weight: 10, is_redline: false },
      { module: "抹布/垃圾/地面", item: "垃圾处理", standard: "所有垃圾收好并丢到对街垃圾站，店内不留满垃圾袋", weight: 15, is_redline: false },
      { module: "抹布/垃圾/地面", item: "吸尘/外摆/拖地", standard: "全店吸尘；外摆桌椅和广告牌收回；按配比拖地并倒污水", weight: 20, is_redline: false },
      { module: "闭店安全", item: "机器/排插关闭", standard: "所有机器、排插、相关电源逐项检查关闭", weight: 25, is_redline: false },
      { module: "闭店安全", item: "灯光/遥控器", standard: "全店灯关闭；白色小遥控器放最外侧桌面", weight: 10, is_redline: false },
      { module: "闭店安全", item: "警报&锁门", standard: "按正确步骤设置警报，听到倒计时后离店，锁门后再拉一下确认", weight: 30, is_redline: false }
    ]
  }
];
